# **Coal Supply Network Optimization in India's Energy Capital**

#### I have created a single notebook for entire problem-solving from adding new variables, computing and optimizing the problem.

## **Loading the data**

In [1]:
import pandas as pd 
import numpy as np
import os

In [2]:
base_path = os.path.dirname(os.getcwd())

In [16]:
distances = pd.read_csv("../Datasets/optimization_Dataset - Distances.csv")
freight = pd.read_csv("../Datasets/Optimization_Dataset - Frieght_Rates.csv")
mines = pd.read_csv("../Datasets/Optimization_Dataset - Mines.csv")
plants = pd.read_csv("../Datasets/Optimization_Dataset - Plants.csv")

In [9]:
print(distances.columns.tolist)

<bound method IndexOpsMixin.tolist of Index(['Mine \ Plant', 'P1 (Vindhyachal)', 'P2 (Singrauli STPS)',
       'P3 (Rihand)', 'P4 (Obra)', 'P5 (Anpara)', 'P6 (Renusagar)',
       'P7 (Essar Mahan)'],
      dtype='object')>

In [10]:
distances.head()

,Mine \ Plant,P1 (Vindhyachal),P2 (Singrauli STPS),P3 (Rihand),P4 (Obra),P5 (Anpara),P6 (Renusagar),P7 (Essar Mahan)
0,M1 (Jayant),17.3,17.1,39.8,76.2,23.5,23.8,85.6
1,M2 (Dudhichua),66.5,66.3,89.0,55.5,43.2,43.5,43.2
2,M3 (Nigahi),17.3,17.1,39.8,76.2,23.5,23.8,85.6
3,M4 (Krishnashila),14.3,14.1,36.8,76.6,23.9,24.2,86.0
4,M5 (Bina),22.5,22.3,45.0,66.6,13.9,14.1,75.9

In [17]:
distances.set_index("Mine \\ Plant", inplace=True)
distances.head()

,P1 (Vindhyachal),P2 (Singrauli STPS),P3 (Rihand),P4 (Obra),P5 (Anpara),P6 (Renusagar),P7 (Essar Mahan)
Mine \ Plant,,,,,,,
M1 (Jayant),17.3,17.1,39.8,76.2,23.5,23.8,85.6
M2 (Dudhichua),66.5,66.3,89.0,55.5,43.2,43.5,43.2
M3 (Nigahi),17.3,17.1,39.8,76.2,23.5,23.8,85.6
M4 (Krishnashila),14.3,14.1,36.8,76.6,23.9,24.2,86.0
M5 (Bina),22.5,22.3,45.0,66.6,13.9,14.1,75.9

## **Calculating Cost Matrix**

Cost matrix is a table where each cell tells you: 'How many rupees it costs to send 1 tonne of coal from this mine to that plant.'

In [ ]:
def get_freight_rate(d):
    if d <= 100: return 216
    elif d <= 125: return 389.6
    elif d <= 150: return 448.9
    elif d <= 175: return 488.7
    elif d <= 200: return 532.2
    elif d <= 275: return 672.5
    elif d <= 350: return 797.2
    elif d <= 425: return 926
    elif d <= 500: return 1054.7
    elif d <= 600: return 1228
    elif d <= 700: return 1398.7
    elif d <= 730: return 1435.6
    else: return 1484


cost_matrix = distances.copy() # Cost Matrix Created Here
CTS = 55 # CTS = Coal Terminal Surcharge

for mine in distances.index:
    for plant in distances.columns:
        d = distances.loc[mine, plant]
        cost_matrix.loc[mine, plant] = get_freight_rate(d) + (CTS if d > 100 else 0)

print(cost_matrix.head())

                   P1 (Vindhyachal)  P2 (Singrauli STPS)  P3 (Rihand)  \
Mine \ Plant
M1 (Jayant)                   216.0                216.0        216.0
M2 (Dudhichua)                216.0                216.0        216.0
M3 (Nigahi)                   216.0                216.0        216.0
M4 (Krishnashila)             216.0                216.0        216.0
M5 (Bina)                     216.0                216.0        216.0

                   P4 (Obra)  P5 (Anpara)  P6 (Renusagar)  P7 (Essar Mahan)
Mine \ Plant
M1 (Jayant)            216.0        216.0           216.0             216.0
M2 (Dudhichua)         216.0        216.0           216.0             216.0
M3 (Nigahi)            216.0        216.0           216.0             216.0
M4 (Krishnashila)      216.0        216.0           216.0             216.0
M5 (Bina)              216.0        216.0           216.0             216.0

In [21]:
cost_matrix.to_csv("../Outputs/cost_matrix_derived.csv")